### ISSUE TITLE
thread local test

### ISSUE THREAD

**Issue by zhouxianjun** [vicanso/async-local-storage#1]
RT:
```js
const als = require('async-local-storage');
als.enable();
let sleep = n => {
    return new Promise(ok => {
        setTimeout(() => ok(), n);
    });
};
let doit = async (n) => {
    await sleep(3000);
    console.log(`doit ${n}: ${als.get('id')}`);
};

global.__a = 0;
setInterval(async () => {
    let value = Math.random();
    als.set('id', value);
    console.log(`a: ${value}`);
    await doit('a');
}, 1000);
setInterval(async() => {
    let value = Math.random();
    als.set('id', value);
    console.log(`b: ${value}`);
    await doit('b');
}, 1000);
```

// print
a: 0.37037671460949206
b: 0.9374930852905572
a: 0.4802650440623768
b: 0.8712013565643415
a: 0.31939900533078425
b: 0.2948936063257914
doit a: 0.31939900533078425
doit b: 0.2948936063257914
a: 0.0540918765065832
b: 0.6340173327025751
doit a: 0.0540918765065832
doit b: 0.6340173327025751
a: 0.6644920305032487
b: 0.15058185161722482
doit a: 0.6644920305032487
doit b: 0.15058185161722482
a: 0.954869207760314
b: 0.24920446605439084

其中 ：
a: 0.37037671460949206
b: 0.9374930852905572
a: 0.4802650440623768
b: 0.8712013565643415
这几个消失了。。。，请问方便讨论下么？

**Comment by zhouxianjun** [comment]
经过多次测试 前两次 必定消失。。。这是为什么？

**Comment by zhouxianjun** [comment]
我换一种方式测试又可以了。。。请看：
####  CLS class
```js
const als = require('async-local-storage');
als.enable();
const A = require('./cls-a');
for (let i = 0; i < 10; i++) {
    setImmediate(() => A.say(`Alone${i}`));
}
```
#### A class
```js
const als = require('async-local-storage');
const B = require('./cls-b');
class CLS_A {
    static async say(name) {
        let value = Math.random();
        console.log(`start ${name} ${value}`);
        als.set('id', value);
        await B.something1(name);
        await B.something2(name);
        als.remove();
        console.log(`end ${name} ${value}`);
    }
}
module.exports = CLS_A;
```
#### B class
```js
const als = require('async-local-storage');
class CLS_B {
    static async something1(name) {
        let id = als.get('id');
        console.log(`something1 name: ${name}, id: ${id}`);
        sleep(random(500, 1000));
    }

    static async something2(name) {
        let id = als.get('id');
        console.log(`something2 name: ${name}, id: ${id}`);
        sleep(random(500, 1000));
    }
}
module.exports = CLS_B;
let sleep = n => {
    return new Promise(ok => {
        setTimeout(() => ok(), n);
    });
};

function random(min, max){
    let r = Math.random() * (max - min);
    let re = Math.round(r + min);
    re = Math.max(Math.min(re, max), min);

    return re;
}
```
### print
start Alone0 0.8217422489517776
something1 name: Alone0, id: 0.8217422489517776
start Alone1 0.6973758939343586
something1 name: Alone1, id: 0.6973758939343586
start Alone2 0.9697994864453081
something1 name: Alone2, id: 0.9697994864453081
start Alone3 0.14306666560441594
something1 name: Alone3, id: 0.14306666560441594
start Alone4 0.20951578576105723
something1 name: Alone4, id: 0.20951578576105723
start Alone5 0.7323871895938974
something1 name: Alone5, id: 0.7323871895938974
start Alone6 0.5422042354649368
something1 name: Alone6, id: 0.5422042354649368
start Alone7 0.5673622633032354
something1 name: Alone7, id: 0.5673622633032354
start Alone8 0.6788618476576418
something1 name: Alone8, id: 0.6788618476576418
start Alone9 0.9064756539366294
something1 name: Alone9, id: 0.9064756539366294
something2 name: Alone0, id: 0.8217422489517776
something2 name: Alone1, id: 0.6973758939343586
something2 name: Alone2, id: 0.9697994864453081
something2 name: Alone3, id: 0.14306666560441594
something2 name: Alone4, id: 0.20951578576105723
something2 name: Alone5, id: 0.7323871895938974
something2 name: Alone6, id: 0.5422042354649368
something2 name: Alone7, id: 0.5673622633032354
something2 name: Alone8, id: 0.6788618476576418
something2 name: Alone9, id: 0.9064756539366294
end Alone0 0.8217422489517776
end Alone1 0.6973758939343586
end Alone2 0.9697994864453081
end Alone3 0.14306666560441594
end Alone4 0.20951578576105723
end Alone5 0.7323871895938974
end Alone6 0.5422042354649368
end Alone7 0.5673622633032354
end Alone8 0.6788618476576418
end Alone9 0.9064756539366294

**Comment by vicanso** [comment]
@zhouxianjun  首先你看看这段代码：

```js
setInterval(async () => {
  let value = Math.random();
  als.set('id', value);
  console.log(a: ${value});
  await doit('a');
}, 1000);
```

这里其实是只生成了一个setInterval，它的调用链一直都是同样的，所以你所看到的不见了前面两个，其实你是一直在修改同一个调用链的数据

而你第二个例子，代码是：
```js
for (let i = 0; i < 10; i++) {
    setImmediate(() => A.say(`Alone${i}`));
}
```

你这是多次的调用了setImmediate，每次的调用链就不一样了，所以你这样就得到了你想要的效果。

**Comment by zhouxianjun** [comment]
哦，我刚才还发现一个问题就是你里面的map会有遗留，我怀疑会对内存有影响

**Comment by zhouxianjun** [comment]
使用Promise的时候，例如我的第二个test，我查看了你的map，还有很多并未调用destroy，所以map的数据未删除，不知道会不会越来越多。
官方：https://nodejs.org/dist/latest-v8.x/docs/api/async_hooks.html#async_hooks_destroy_asyncid
我理解的意思是引用对象在GC之前是不会回调destroy的。

**Comment by vicanso** [comment]
@zhouxianjun  destroy 的调用我感觉是非实时的，我一会增加一个测试脚本，你可以试一下

**Comment by vicanso** [comment]
@zhouxianjun  可以使用[loop](https://github.com/vicanso/async-local-storage/blob/master/test/support/loop.js)这个来测试一下

```bash
count:1780, als map size:106 memory:51
count:1790, als map size:138 memory:51
count:1800, als map size:170 memory:51
count:1810, als map size:202 memory:51
count:1820, als map size:232 memory:51
count:1830, als map size:264 memory:52
count:1840, als map size:296 memory:52
count:1850, als map size:40 memory:51
```

**Comment by zhouxianjun** [comment]
ok，我周一去公司试试。你那个里面的 时间是干嘛用的啊，还有那个use函数。

**Comment by vicanso** [comment]
就是方便可以获取函数的处理时间，不过我现在也没使用到，后期我再看看应用场景

**Comment by zhouxianjun** [comment]
恩，经过一天的验证这个destroy不是实时的，估计是等GC。
