### ISSUE TITLE
state stored in "global variable"

### ISSUE THREAD

**Issue by vinczedani** [vicanso/async-local-storage#14]
Dear @vicanso,

I am really interested in your library as it would help us track a request flow in our logs in an elegant way. I was checking the implementation, and I noticed currentId is stored in a simple let. https://github.com/vicanso/async-local-storage/blob/master/als.js#L55
My question is, what happens if multiple requests come in and calls the before async hook while another request is "in the system". The old currentId is always overwritten when a new request comes in, right?
My understanding of async hooks is limited, so there is probably something I don't see, so I would be really happy if you could explain this part, and how currentId stays valid, during parallel requests.
Thanks in advance,
Daniel

**Comment by vinczedani** [comment]
another thing, I see you use [asyncHooks.currentId() function](https://github.com/vicanso/async-local-storage/blob/master/als.js#L98), but I can't seem to find it in any NodeJS documentation. Can you please provide me a link if there is any, for some documentation about this function?

**Comment by vicanso** [comment]
The first node is single process,  in which there is one main thread for javascript engine and also some threads for io. Therefore it can't be executed parallel in main thread. Even though multiple requests come in, only one will be handled in main thread. When this one is finished or waiting for io, the next will be handled in main thread.

Async hook will change the `asyncId` when the context is changed. For example, before the call back function is called,  the `before` function of async hook will be called and the `asyncId` parameter will be changed for the callback. So `async-local-storage` changes `currentId` to match the new context.

`asyncHooks.currentId` function is in early version of node v8.x, which is deprecated. [DEP0070](https://nodejs.org/dist/latest-v8.x/docs/api/deprecations.html#deprecations_dep0070_async_hooks_currentid)

**Comment by vinczedani** [comment]
I see, thanks for the explanation! Really nice lib!
