### ISSUE TITLE
Unexpected behaviour with Node version 12.1.0

### ISSUE THREAD

**Issue by vinczedani** [vicanso/async-local-storage#15]
Hey @vicanso 
I came across a strange behaviour using als and NodeJS v12.1.0 It seems like the triggerIds are messed up a bit. I am not assuming your library is working bad or anything, I am just here to get some help as you probably know async_hooks better then me.

I created a sample application to reproduce the behaviour we have in our real codebase.

```const http = require('http');
const app = require('connect')();
const request = require('request');
const als = require('async-local-storage');
const hooks = require('async_hooks');

als.enable();

app.use((req, res, next) => {
    als.set('foo', { b: 'bar' });

    next();
});

app.use((req, res) => {
    request.get('https://google.com', (err, resp, body) => {
        console.log('Response from google in ' + hooks.executionAsyncId() + ' triggered by ' + hooks.triggerAsyncId());
        const asd = als.get('foo');
        console.log(asd);
        return res.end(JSON.stringify(asd));
    });
});

//create node.js http server and listen on port
http.createServer(app).listen(3000, function() {
    // eslint-disable-next-line no-console
    console.log('Your server is listening on port 3000 (http://localhost:3000)');
});
```

I piped the logs to a file. It can be found here: https://pastebin.com/xyC5AhH4
I refreshed localhost:3000 once using chrome browser. (in the logs it looks like 2 requests arrived, but I guess it is not related to als at all)

Some part of the logs I think might be important: 
```
4(TCPSERVERWRAP) init by 1
...
7(TCPWRAP) init by 4
8(Timeout) init by 7
9(HTTPINCOMINGMESSAGE) init by 7
10(Timeout) init by 7
11(TickObject) init by 7
destroy 11
set foo:[object Object] to 9
...
12(Immediate) init by 9
...
19(TickObject) init by 12
20(HTTPINCOMINGMESSAGE) init by 19
...
destroy 20
...
251(TickObject) init by 20
Response from google in 251 triggered by 20
252(TickObject) init by 251
get foo:undefined from 251
undefined
```

20 is destroyed before my callbacks are initiated by it, so the context set to 9 is lost at the point when the callback passed to request is called. Do you have any tip on how to resolve this problem?
We would like to use async_hooks and your lib to track request ids during our logging without the need to pass a context object everywhere.

Thanks in advance,
Daniel

Edit: using node v10.15.3 (npm v6.9.0) the lib works just as expected

**Comment by vinczedani** [comment]
I created an issue in the NodeJS repo, as it seems to be an issue there.
https://github.com/nodejs/node/issues/27594

**Comment by vicanso** [comment]
@vinczedani  The `executionAsyncId ` function returns a destroy id, then this issue occurs. But I haven't found the reason of it and I suggest you use the version 10.

Besides, when `http://127.0.0.1:3000/` is accessed  by browser,  it also gets the request of `http://127.0.0.1:3000/favicon.ico`. Therefore `set foo:[object Object] to 9` occurs twice in your logs, and the `executionAsyncId` is the same, and you set data in the same scope in two requests. The reason of this situation is that the `middleware` of `connect` isn't async executed and the two requests are used the same tcp connection.

If you want to set data in different scopes, you can use like this:

- run async execution at the head of middleware functions

```js
app.use((req, res, next) => {
    // async execution
    setImmediate(next);
})
app.use((req, res, next) => {
    als.set('foo', { b: 'bar' });
    next();
});
```

-  close tcp connection each time

```js
app.use((req, res) => {
    request.get('https://google.com', (err, resp, body) => {
        console.log('Response from google in ' + hooks.executionAsyncId() + ' triggered by ' + hooks.triggerAsyncId());
        const asd = als.get('foo');
        console.log(asd);
        // close tcp connection each time
        res.setHeader('Connection', 'close');
        return res.end(JSON.stringify(asd));
    });
});
```

**Comment by vinczedani** [comment]
NodeJS 12.2.0. is released and the issue is fixed!
