### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by sonicoder86** [vicanso/async-local-storage#3]
I have seen the error in Travis build:

    1) async-local-storage get id(http) success:
        Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

Does it mean the package is malfunctioning?

**Comment by vicanso** [comment]
@blacksonic Because the `get id(http) success` test will get the request of `http://www.baidu.com/`,  sometimes it runs over 2000ms.
