### ISSUE TITLE
在请求很大的情况下， map会不会很大， 导致内存爆掉

### ISSUE THREAD

**Issue by sapolang** [vicanso/async-local-storage#4]

**Comment by vicanso** [comment]
理论上是存在这样的可能性，不过正常来说，函数在处理完成之后，则会删除，量级不会太大。
如果你还是担心，建议你先启用之后，只设置相关的数据，定时调用`size()`函数获取，如果超过你设置的值，则`disable()`，收集一定的数据之后，再决定是否采用
