### ISSUE TITLE
TickObject

### ISSUE THREAD

**Issue by sinnott74** [vicanso/async-local-storage#5]
What is the reason behind:

```
if (type === 'TickObject') {
  return;
}
```
during asyncHooks.createHook - init

**Comment by vicanso** [comment]
@sinnott74  I found that `TickObject` is triggered frequently. It doesn't matter whether  it's ignored. So I wrote this code for less memory.

Is there any problem?

**Comment by sinnott74** [comment]
Context is lost when using passport & passport-jwt as it uses `TickObject`. I was more curious than anything. Love the simplicity of the package. Closing the issue

**Comment by vicanso** [comment]
@sinnott74  I will fix it in next version, thanks very much
